# 행렬

행렬은 사각형 형태로 숫자를 나열하는 것을 의미.  

![matrix](../src/2/matrix1.png)

i : 행번호  
j : 열번호



<br>

## 행렬의 덧셈과 뺄셈

어떤 벡터가 다른 벡터와 덧셈이 가능하듯이, 행렬간에도 덧셈, 뺄셈도 가능하다.  

단, 각 행렬의 동일 위치에 대응하는 원소끼리 연산이 가능 그리고 이 때, 연산하는 원소의 행번호와 열번호가 동일해야 함.

![2](../src/2/matrix2.png)

<br>

## 행렬의 스칼라 곱

Matrix scalar multiplicaton 은 스칼라와 행렬을 곱하는 '스칼라 X 행렬'을 의미한다.  
  

예를 들어 기존 행렬에 스칼라 2를 곱하는 것은 각 행벡터 나 열벡터가 2배로 늘어난다는 것을 의미한다.

![3](../src/2/matrix3.png)



<br>

## 행렬의 원소 곱

Matrix element-wise multiplication 은 크기가 동일한 두 행렬에서 동일한 위치의 원소들끼리 서로 곱하는 것을 의미.  

단, 행렬의 원소 곱이 가능하려면 두 행령의 크기가 동일해야 함.


![4](../src/2/matrix4.png)

<br>

## 행렬 곱

Matrix multiplication 은 행렬 끼리 곱하는 것을 의미.  

행렬 곱은 일반적인 곱셈과 달리 전제 조건이 만족되어야 가능.  

![5](../src/2/matrix5.png)  

![6](../src/2/matrix6.png)  

### 행렬 연산의 특징

![8](../src/2/matrix8.png) 

![9](../src/2/matrix9.png)

<br>

1. A+B = B+A
2. A+(B+C) = (A+B)+C
3. A(BC) = (AB)C
4. A(B+C) = AB+AC
5. (B+C)A = BA+CA
6. A(B-C) = AB-AC
7. (B-C)A = BA-BC
8. (B-C)A = BA-BC
9. a(B+C) = aB+aC
10. a(B-C) = aB-aC
11. (a+b)C = aC+bC
12. (a-b)C = aC-bC
13. a(BC) = (aB)C = B(aC)

<br>

## 행렬 대각합

행렬 A가 정사각 행렬일 때, 행렬 A의 대각합(trace) 대각 원소를 모두 더한 값을 의미합니다.  

tr(A)로 표기합니다.

![6](../src/2/matrix7.png)

<br><br>

# 파이썬

In [6]:
# 행렬의 덧셈

A = [[2, 7], [3, 4], [6, 1]]
B = [[1, 4], [4, -1], [2, 5]]

n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] + B[i][j]
        row.append(val)

    res.append(row)

print(res)

import m_func as f

# 함수
f.add(A,B)

[[3, 11], [7, 3], [8, 6]]


[[3, 11], [7, 3], [8, 6]]

In [15]:
# 행렬의 뺄셈
A = [[2, 7], [3, 4], [6, 1]]
B = [[1, 4], [4, -1], [2, 5]]

n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] - B[i][j]
        row.append(val)

    res.append(row)

print(res)

# 함수
import importlib
import m_func as f

# m_func 모듈 다시 불러오기
importlib.reload(f)
f.subtract(A,B)

[[1, 3], [-1, 5], [4, -4]]


[[1, 3], [-1, 5], [4, -4]]

In [19]:
# 행렬의 스칼라 곱

A = [[2, 7], [3, 4], [6, 1]]
b = 2

n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = b * A[i][j]
        row.append(val)

    res.append(row)

print(res)

f.scalar_mul(b, A)

[[4, 14], [6, 8], [12, 2]]


[[4, 14], [6, 8], [12, 2]]

In [23]:
# 행렬의 원소 곱
A = [[1, 5], [6, 4], [2, 7]]
B = [[5, -1], [1, 2], [4, 1]]

n = len(A)
p = len(A[0])

res = []
for i in range(0, n):
    row = []
    for j in range(0, p):
        val = A[i][j] * B[i][j]
        row.append(val)
    res.append(row)

print(res)
importlib.reload(f)
f.ele_product(A, B)

[[5, -5], [6, 8], [8, 7]]


[[5, -5], [6, 8], [8, 7]]

In [26]:
# 행렬 곱
A = [[2, 7], [3, 4], [5, 2]]
B = [[3, -3, 5], [-1, 2, -1]]

n = len(A)
p1 = len(A[0])
p2 = len(B[0])

res = []

for i in range(0, n):
    row = []
    for j in range(0, p2):
        val = 0
        for k in range(0, p1):
            val += A[i][k] * B[k][j]
        row.append(val)
    res.append(row)
print(res)

importlib.reload(f)
f.matmul(A, B)

[[-1, 8, 3], [5, -1, 11], [13, -11, 23]]


[[-1, 8, 3], [5, -1, 11], [13, -11, 23]]

# Numpy

In [35]:
import numpy as np

#행렬의 덧셈
A = np.array([[2, 7], [3, 4], [6, 1]])
B = np.array([[1, 4], [4, -1], [2, 5]])
C = A + B
print(C)
print()

# 뺄셈
C = A - B
print(C)
print()

# 스칼라 곱
b = 2
C = b*A
print(C)
print()


# 행렬의 원소 곱
A = np.array([[1, 5], [6, 4], [2, 7]])
B = np.array([[5, -5], [1, 2], [4, 1]])
C = np.multiply(A,B)
print(C)
print()


# 행렬 곱
A = np.array([[1, 5], [6, 4], [2, 7]])
B = np.array([[5, -5, 1], [2, 4, 1]])
C = np.matmul(A,B)
print(C)
print()

[[ 3 11]
 [ 7  3]
 [ 8  6]]

[[ 1  3]
 [-1  5]
 [ 4 -4]]

[[ 4 14]
 [ 6  8]
 [12  2]]

[[  5 -25]
 [  6   8]
 [  8   7]]

[[ 15  15   6]
 [ 38 -14  10]
 [ 24  18   9]]

