# Vector

벡터 = 스칼라의 집합 & 행렬을 구성하는 기본 단위.  
스칼라와는 달리 크기(Magnitude) 와 방향(Direction) 들을 나타내는 개념입니다.  
**굵은 소문자**를 표기에 사용

![vector](..//src/2/vector.png)  

행 벡터와 열 벡터로 나뉘며, 특별한 언급이 없으면 열 벡터를 의미한다.

크기와 방향이 없는 벡터는 '0'벡터(zero vector) 로 부른다.  
벡터에서 '-'부호를 붙인다는 것은 크기는 그대로 **방향만 반대**를 의미한다.

<br>

## 벡터의 덧셈과 뺄셈

![vector1](../src/2/vector1.png)

a + b = b + a  
두 벡터를 이용하면 평행사변형이 만들어진다는 사실을 알 수 있으며, 벡터의 덧셈 결과는 벡터의 시작 지점으로부터 평행사변형의 대각선을 구성하는 벡터임  

<br>

![vector2](../src/2/vector2.png)

a - b = a + (-b)

a = b + (a - b)의 합집합으로 볼 수 도 있다.


### 파이썬

In [2]:
# 덧셈
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] + v[i]
    w.append(val)
print(w)

[5, 7, 9]


In [3]:
# 덧셈 함수 구현
def v_add(u, v):
    """
    벡터의 덧셈
    input: 더하고자 하는 벡터 u, v
    output: 덧셈 결과 벡터 w
    """
    n = len(u)
    w = []

    for i in range(0, n):
        val = u[i] + v[i]
        w.append(val)
    
    return w

In [4]:
u = [7, 8, 9]
v = [12, 11, 10]

v_add(u, v)

[19, 19, 19]

In [5]:
# 뺄셈
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] - v[i]
    w.append(val)
print(w)

[-3, -3, -3]


In [6]:
# 뺄셈 함수 구현
def v_subtract(u, v):
    """
    벡터의 뺄셈
    input: 빼고자 하는 벡터 u, v
    output: 뺄셈 결과 벡터 w
    """
    n = len(u)
    w = []

    for i in range(0, n):
        val = u[i] - v[i]
        w.append(val)
    
    return w

In [7]:
u = [7, 8, 9]
v = [12, 11, 10]

v_subtract(u, v)

[-5, -3, -1]

<br><br>

### numpy

In [18]:
# 덧셈
import numpy as np

u = np.array([1,2,3])
v = np.array([4,5,6])
w = u + v
print(w)

[5 7 9]


In [19]:
# 뺄셈

u = np.array([1,2,3])
v = np.array([4,5,6])
w = u - v
print(w)

[-3 -3 -3]


<br>

## 벡터의 곱셈과 뺄셈

벡터에 2를 곱한다는 것은 2배 만큼 크기가 커지는것을 의미.  
하지만 무조건 크키만 바뀔 뿐만 아니라, 방향도 바뀔 수 있다.  

<br>

- 벡터 기본 연산의 성질

> 벡터 u,v,w 그리고 스칼라 a,b 존재 할때, 다음과 같은 성질이 성립할 수 있다.

1. u + v = v + u
2. (u + v) + w = u + (v + w)
3. u + 0 = 0 + u = u
4. u + (-u) = 0
5. a(bu) = (ab)u
6. a(u + v) = au + av
7. (a + b)u = au + bu

### 파이썬

In [8]:
# 곱셈
u = [2, 4, 2]
a = 3

n = len(u)
w = []

for i in range(0, n):
    val = a * u[i]
    w.append(val)

print(w)

[6, 12, 6]


In [9]:
# 곱셈 함수
def scalar_v_mul(a, u):
    """
    벡터의 스칼라 곱
    input: scalar a, vector list u
    output: 곱 결과 w
    """
    n = len(u)
    w = []

    for i in range(0, n):
        val = a * u[i]
        w.append(val)
    
    return w

In [10]:
u = [2, 4, 3]
a = 3

scalar_v_mul(a, u)

[6, 12, 9]

In [11]:
## 벡터의 원소 곱
u = [1, 2, 4]
v = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * v[i]
    w.append(val)

print(w)

[7, 6, 8]


In [12]:
# 벡터 원소 곱 함수
def v_mul(u, v):
    """
    벡터의 원소 곱
    input: 곱하는 두 원수 u, v
    output: 곱한 벡터 w
    """
    n = len(u)
    w = []

    for i in range(0, n):
        val = u[i] * v[i]
        w.append(val)
    
    return w

In [13]:
# 나눗셈
u = [6, 5, 9]
v = [2, 2, -3]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] / v[i]
    w.append(val)

print(w)

[3.0, 2.5, -3.0]


In [14]:
# 나눗셈 함수
def v_div(u, v):
    """
    벡터 element-wise 나눗셈
    input: 나누고자 하는 벡터 u, v
    output: 나눈 결과값 벡터 w
    """
    n = len(u)
    w = []

    for i in range(0, n):
        val = u[i] / v[i]
        w.append(val)
    
    return w

In [15]:
u = [7, 5, -9]
v = [2, 2, 3]

v_div(u, v)

[3.5, 2.5, -3.0]

<br>

### numpy

In [20]:
# 스칼라 곱
a = 3
u = np.array([1,2,4])
w = a * u
print(w)

[ 3  6 12]


In [22]:
# 원소 곱
u = np.array([1,2,4])
v = np.array([7,3,2])

w = u * v
print(w)

[7 6 8]


In [23]:
# 나눗셈
u = np.array([6,5,-9])
v = np.array([2,2,-3])
w = u / v
print(w)

[3.  2.5 3. ]
