In [69]:
import importlib
import mm_func as f
importlib.reload(f)

import sys
sys.path.append('../code')
import m_func as f2

import numpy as np

# 다양한 행렬

## 파이썬

### transpose

In [14]:
# 전치행렬
A = [[1, 5], [3, 4], [6, 2]]

n = len(A)  # 3
p = len(A[0])   #2

At = []
for i in range(0, p):
    row = []
    for j in range(0, n):
        val = A[j][i]
        row.append(val)
    At.append(row)

print(At)

import mm_func as f
f.transpose(A)

[[1, 3, 6], [5, 4, 2]]


[[1, 3, 6], [5, 4, 2]]

### Symmetric

In [27]:
# 대칭행렬
A = [[1,0,2], [0,2,1], [2,1,1]]
At = f.transpose(A)
print(At)

print(A==At)    # 둘이 정말 같은 행렬임을 볼 수 있다.


AA = A
for i in range(0, 9):
    AA = f2.matmul(AA, A)
    print("행렬 A의", i+2, "제곱은", AA)


## AAt => 대칭행렬임을 보자.
A = [[1,0,3], [2,1,4], [0,1,1]]
At = f.transpose(A)

print(f2.matmul(A, At))
print(f2.matmul(At, A))

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]
True
행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]
[[10, 14, 3], [14, 21, 5], [3, 5, 2]]
[[5, 2, 11], [2, 2, 5], [11, 5, 26]]


### Diagonal

In [21]:
# 대각 행렬
A = [[1,2,3], [4,5,6], [7,8,9]]

n = len(A)
D = []

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i == j:
            row.append(A[i][j])
        else:
            row.append(0)
    D.append(row)

print(D)

print(f.diag(A))    # 대각행렬 구하기
print(f.diag_ele(A))# 대각원소 구하기

a = [1, 9, 5]
print(f.ele2diag(a))# 대각원소로 대각행렬 구하기
print()


# 일반행렬에 대각행렬을 곱했을 때
A = [[1,2,3], [4,5,6], [7,8,9]]
D = f.ele2diag([2,1,1])

AD = f2.matmul(A,D)
print(AD)

DA = f2.matmul(D,A)
print(DA)
print()


D = f.ele2diag([1,3,4])

AD = f2.matmul(A,D)
print(AD)

DA = f2.matmul(D,A)
print(DA)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]
[[1, 0, 0], [0, 5, 0], [0, 0, 9]]
[1, 5, 9]
[[1, 0, 0], [0, 9, 0], [0, 0, 5]]

[[2, 2, 3], [8, 5, 6], [14, 8, 9]]
[[2, 4, 6], [4, 5, 6], [7, 8, 9]]

[[1, 6, 12], [4, 15, 24], [7, 24, 36]]
[[1, 2, 3], [12, 15, 18], [28, 32, 36]]


### Identity

In [34]:
# 항등행렬
f.identity(5)
print()

A = [[1,2,3],[4,5,6],[7,8,9]]
I = f.identity(3)

AI = f2.matmul(A,I)
print(AI)
print()

IA = f2.matmul(I,A)
print(IA)
print()
## 동일하다


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]



### Zero

In [42]:
f.zero_mat(3, 2)


[[0, 0], [0, 0], [0, 0]]

### Triangular

In [45]:
A = [[1,2,3],[4,5,6],[7,8,9]]

print(f.u_tri(A))
print(f.l_tri(A))

[[1, 2, 3], [0, 5, 6], [0, 0, 9]]
[[1, 0, 0], [4, 5, 0], [7, 8, 9]]


### Toeplitz

In [51]:
a = [1, 0, -2, -4]
b = [1, 3, 5, 7, 9]
f.toeplitz(a,b)

[[1, 3, 5, 7, 9], [0, 1, 3, 5, 7], [-2, 0, 1, 3, 5], [-4, -2, 0, 1, 3]]

### Bidiagonal

In [55]:
A = [[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]]
print(f.u_bidiag(A))    # upper bidiagonal matrix

[[1, 2, 0, 0], [0, 3, 4, 0], [0, 0, 7, 9], [0, 0, 0, 3]]


In [56]:
A = [[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]]
print(f.l_bidiag(A))    # upper bidiagonal matrix

[[1, 0, 0, 0], [5, 3, 0, 0], [0, 1, 7, 0], [0, 0, 1, 3]]


### Householder 

In [70]:
a = [1, 0, 2, 3]
f.householder(a)

[[0.8571428571428572, 0.0, -0.2857142857142857, -0.42857142857142855],
 [0.0, 1.0, 0.0, 0.0],
 [-0.2857142857142857, 0.0, 0.4285714285714286, -0.8571428571428571],
 [-0.42857142857142855, 0.0, -0.8571428571428571, -0.2857142857142856]]

## Numpy

### transpose

In [22]:
# 전치 행렬
import numpy as np

A = np.array([[1,5], [3,4], [6,2]])
At = np.transpose(A)
print(At)

[[1 3 6]
 [5 4 2]]


### Symmetric

In [32]:
## 대칭 행렬
A = np.array([[1,0,2], [0,2,1], [2,1,1]])
print(A)

At = np.transpose(A)
print(At)

A == At

AA = A
for i in range(0, 9):
    AA = np.matmul(AA, A)
    print("행렬 A의", i+2, "제곱은")
    print(AA)
    print("="*10)

# 역행렬과의 곱이 대칭행렬?
A = np.array([[1,0,3], [2,1,4], [0,1,1]])
At = np.transpose(A)
print(np.matmul(A, At))
print(np.matmul(At, A))

[[1 0 2]
 [0 2 1]
 [2 1 1]]
[[1 0 2]
 [0 2 1]
 [2 1 1]]
행렬 A의 2 제곱은
[[5 2 4]
 [2 5 3]
 [4 3 6]]
행렬 A의 3 제곱은
[[13  8 16]
 [ 8 13 12]
 [16 12 17]]
행렬 A의 4 제곱은
[[45 32 50]
 [32 38 41]
 [50 41 61]]
행렬 A의 5 제곱은
[[145 114 172]
 [114 117 143]
 [172 143 202]]
행렬 A의 6 제곱은
[[489 400 576]
 [400 377 488]
 [576 488 689]]
행렬 A의 7 제곱은
[[1641 1376 1954]
 [1376 1242 1665]
 [1954 1665 2329]]
행렬 A의 8 제곱은
[[5549 4706 6612]
 [4706 4149 5659]
 [6612 5659 7902]]
행렬 A의 9 제곱은
[[18773 16024 22416]
 [16024 13957 19220]
 [22416 19220 26785]]
행렬 A의 10 제곱은
[[63605 54464 75986]
 [54464 47134 65225]
 [75986 65225 90837]]
[[10 14  3]
 [14 21  5]
 [ 3  5  2]]
[[ 5  2 11]
 [ 2  2  5]
 [11  5 26]]


### Diagonal

In [30]:
## 대각행렬
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.diag(A)
print(D)
print(np.diag(D))   # 구한 대각원소를 다시 대각행렬함수에 넣으면, 행렬을 구할 수 있다.
print()

D = np.diag([1,3,4])
print(D)
print()

AD = np.matmul(A,D)
print(AD)
DA = np.matmul(D,A)
print(DA)

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]

[[1 0 0]
 [0 3 0]
 [0 0 4]]

[[ 1  6 12]
 [ 4 15 24]
 [ 7 24 36]]
[[ 1  2  3]
 [12 15 18]
 [28 32 36]]


### Identity

In [38]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
A = [[1,2,3],[4,5,6],[7,8,9]]
AI = np.matmul(A,I)
print(AI)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [40]:
IA = np.matmul(I,A)
print(IA)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Zero

In [43]:
Z = np.zeros((3,2))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Triangular

In [47]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
AU = np.triu(A)
print(AU)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [48]:
AL = np.tril(A)
print(AL)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


### toeplitz

In [53]:
from scipy.linalg import toeplitz    # numpy는 라이브러리 함수가 없음

A = toeplitz([1, 0, -2, -4], [1, 3, 5, 7, 9])
print(A)

[[ 1  3  5  7  9]
 [ 0  1  3  5  7]
 [-2  0  1  3  5]
 [-4 -2  0  1  3]]


### Bidigonal

In [57]:
A = np.array([[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]])

print(A)

[[1 2 1 3]
 [5 3 4 1]
 [2 1 7 9]
 [2 8 1 3]]


In [61]:
# upper diagonal matrix
diag_ele = np.diag(A)
print(diag_ele)
np.diag(diag_ele)

[1 3 7 3]


array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 3]])

In [64]:
u_diag_ele = np.diag(A, k=1)    # k 는 원소 1칸위에 있는 원소를 의미
print(u_diag_ele)
np.diag(u_diag_ele, k=1)    # k 1칸 위에 위치 시킨 행렬을 구할 수 있음을 의미

[2 4 9]


array([[0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 9],
       [0, 0, 0, 0]])

In [63]:
u_diag = np.diag(diag_ele) + np.diag(u_diag_ele, k=1)
print(u_diag)

[[1 2 0 0]
 [0 3 4 0]
 [0 0 7 9]
 [0 0 0 3]]


In [66]:
# lower diagonal matrix
A = np.array([[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]])
diag_ele = np.diag(A)
print(diag_ele)

np.diag(diag_ele)

[1 3 7 3]


array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 3]])

In [67]:
l_diag_ele = np.diag(A, k=-1)
print(l_diag_ele)

np.diag(l_diag_ele, k=-1)

[5 1 1]


array([[0, 0, 0, 0],
       [5, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [68]:
l_diag = np.diag(diag_ele) + np.diag(l_diag_ele, k=-1)
print(l_diag)

[[1 0 0 0]
 [5 3 0 0]
 [0 1 7 0]
 [0 0 1 3]]


### Householder

In [71]:
v = np.array([1, 0, 2, 3])
n = len(a)
outer_mat = np.outer(v, v)
inner_val = np.inner(v, v)
I = np.identity(n)

H = I - (2/inner_val) * outer_mat
print(H)

[[ 0.85714286  0.         -0.28571429 -0.42857143]
 [ 0.          1.          0.          0.        ]
 [-0.28571429  0.          0.42857143 -0.85714286]
 [-0.42857143  0.         -0.85714286 -0.28571429]]
